### ISSUE TITLE
Issue fatal error if SQLite is not found

### ISSUE THREAD

**Issue by bpe2** [usnistgov/ns3-oran#2]
If the user has included this module, but for whatever reason doesn't have SQLite installed, the module does not enable, and all they get is a little message when configuring ns-3 that easily gets lost in the large mess of other messages from configuring ns-3.

Change the behavior from only showing a message, to exiting with an error, or at least elevate the message to a warning.

**Comment by wdgj** [comment]
Do not plan to error out if SQLite is not found during the compilation process.
