### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by srehan911** [usnistgov/ns3-oran#4]
Hello,

I tried to use the examples but it is throwing the following error:

"error adding symbols: DSO missing from command line"

It sounds like not all the libraries are "directly" specified on the linker command line? It should be an easy fix.

**Comment by wdgj** [comment]
Hi

Which OS are you using and which version of ns-3 are you using?

Are you able to compile ns-3 without the inclusion of the ns3-oran module?

**Comment by srehan911** [comment]
Hi,

Wanted to add that both Torch and OnnxRuntime are built ok. You can also see from the attached picture that the oran module is also processed with no errors.

Also, the VS-code is throwing an error at the inclusion of the "oran-module.h" library as in the picture.


<img width="413" alt="Screenshot 2024-01-09 171248" src="https://github.com/usnistgov/ns3-oran/assets/156026723/af895ddd-4ab5-4547-838b-df6a6bf42a06">


<img width="669" alt="Screenshot 2024-01-09 170737 -2 " src="https://github.com/usnistgov/ns3-oran/assets/156026723/62f30775-4f17-439f-82ee-abafacc75c2b">

**Comment by wdgj** [comment]
For the time being you should try to use the distro's torch package:

`unset LIBTORCHPATH`
`sudo apt install libtorch-dev`
`./ns3 clean`
`./ns3 configure --enable-examples`
`./ns3`

The ONNX runtime library should still work as you have it.

**Comment by srehan911** [comment]
Ok, will do that for now.

Thanks a lot for your support.

**Comment by wdgj** [comment]
An updated version of pytorch should be used with ns-3.41 and this has been reflected in the README.md
